### ISSUE TITLE
[BUG] Melpa folder gets put in the trash on MacOS

### ISSUE THREAD

**Issue by Game-Warrior** [abougouffa/minemacs#130] opened 2023-11-22 15:35 UTC
**Describe the bug**
When I start Emacs it downloads everything from melpa then it puts it in the trash.

**Emacs version**

```elisp
GNU Emacs 29.1 (build 2, aarch64-apple-darwin23.1.0, NS appkit-2487.20 Version 14.1 (Build 23B74)) of 2023-11-13
```

**Checkup list**
- [n/a] You've tested disabling your `config.el` using `MINEMACS_IGNORE_CONFIG_EL=1 emacs`?

**To Reproduce**
1. Open Emacs 
2. Install pacakages from melpa 
3. Try open a packages (fx  dired-nerd-icons)
4. run-hooks: Cannot open load file: No such file or directory, nerd-icons-dired

**Expected behavior**

Not attempt to delete the melpa folder. So I can run installed packages.

**Backtrace**
If the bug rises an error, please attach the full backtrace. To be sure to obtain a backtrace, you should launch Emacs with `MINEMACS_DEBUG=1 emacs` or `emacs --debug-init`.

```elisp

 #f(compiled-function () #<bytecode 0x19819f6297ef>)()
  file-relative-name("/Users/gb/.emacs.d/elpa/dash-2.19.1/dash.el")
  macroexp-warn-and-return("Use -zip-pair instead of -zip to get a list of pai..." (-zip-pair (-map fn list) list))
  dash--zip-lists-or-pair((-zip-pair (-map fn list) list) (-map fn list) list)
  apply(dash--zip-lists-or-pair (-zip-pair (-map fn list) list) ((-map fn list) list))
  macroexp--compiler-macro(dash--zip-lists-or-pair (-zip-pair (-map fn list) list))
  macroexp--expand-all((-zip-pair (-map fn list) list))
  macroexp--expand-all((-zip-pair (-map fn list) list))
;; This repeats hundreds of times
  macroexp--expand-all((-zip-pair (-map fn list) list))
  macroexp--expand-all((-zip-pair (-map fn list) list))
  macroexp--expand-all((-zip-pair (-map fn list) list))
  macroexp--expand-all((-zip (-map fn list) list))
  macroexp--all-forms((lambda (fn list) "Return a list of cons cells where each cell is FN ..." (-zip (-map fn list) list)) 2)
  macroexp--expand-all(#'(lambda (fn list) "Return a list of cons cells where each cell is FN ..." (-zip (-map fn list) list)))
  macroexp--all-forms((defalias '-annotate #'(lambda (fn list) "Return a list of cons cells where each cell is FN ..." (-zip (-map fn list) list))) 1)
  macroexp--expand-all((defalias '-annotate #'(lambda (fn list) "Return a list of cons cells where each cell is FN ..." (-zip (-map fn list) list))))
  macroexpand--all-toplevel((defalias '-annotate #'(lambda (fn list) "Return a list of cons cells where each cell is FN ..." (-zip (-map fn list) list))))
  internal-macroexpand-for-load((defalias '-annotate #'(lambda (fn list) "Return a list of cons cells where each cell is FN ..." (-zip (-map fn list) list))) t)
  load-with-code-conversion("/Users/gb/.emacs.d/elpa/dash-2.19.1/dash.el" "/Users/gb/.emacs.d/elpa/dash-2.19.1/dash.el" nil t)
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_32>(("/Users/gb/.emacs.d/elpa/dash-2.19.1/dash" . 335))
  mapc(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_32> (("/Users/gb/.emacs.d/elpa/dash-2.19.1/dash" . 335)))
  package--reload-previously-loaded(#s(package-desc :name dash :version (2 19 1) :summary "A modern list library for Emacs" :reqs ((emacs (24))) :kind nil :archive nil :dir "/Users/gb/.emacs.d/elpa/dash-2.19.1" :extras ((:url . "https://github.com/magnars/dash.el") (:maintainer "Magnar Sveen" . "magnars@gmail.com") (:authors ("Magnar Sveen" . "magnars@gmail.com")) (:keywords "extensions" "lisp")) :signed nil))
  package-activate-1(#s(package-desc :name dash :version (2 19 1) :summary "A modern list library for Emacs" :reqs ((emacs (24))) :kind nil :archive nil :dir "/Users/gb/.emacs.d/elpa/dash-2.19.1" :extras ((:url . "https://github.com/magnars/dash.el") (:maintainer "Magnar Sveen" . "magnars@gmail.com") (:authors ("Magnar Sveen" . "magnars@gmail.com")) (:keywords "extensions" "lisp")) :signed nil) :reload :deps)
  package-unpack(#s(package-desc :name dash :version (2 19 1) :summary "A modern list library for Emacs" :reqs ((emacs (24))) :kind tar :archive "gnu" :dir nil :extras ((:url . "https://github.com/magnars/dash.el") (:maintainer "Magnar Sveen" . "magnars@gmail.com") (:authors ("Magnar Sveen" . "magnars@gmail.com")) (:keywords "extensions" "lisp")) :signed nil))
  #f(compiled-function (&optional good-sigs) #<bytecode -0xf58d5abb7cafb93>)((#s(epg-signature :status good :key-id "066DAFCB81E42C40" :validity undefined :fingerprint "C433554766D3DDC64221BFAA066DAFCB81E42C40" :creation-time 1630011901 :expiration-time nil :pubkey-algorithm 1 :digest-algorithm 10 :class 0 :version 4 :notations nil)))
  #f(compiled-function () #<bytecode 0x3e1c46cbddc42c2>)()
  package--with-response-buffer-1("https://elpa.gnu.org/packages/" #f(compiled-function () #<bytecode 0x3e1c46cbddc42c2>) :file "dash-2.19.1.tar.sig" :async nil :error-function #f(compiled-function () #<bytecode 0x150c354f3f6550bf>) :noerror t)
  package--check-signature("https://elpa.gnu.org/packages/" "dash-2.19.1.tar" "dash-2.19.1/\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0..." nil #f(compiled-function (&optional good-sigs) #<bytecode -0xf58d5abb7cafb93>))
  #f(compiled-function () #<bytecode -0x1c93fc9a053c2d9>)()
  package--with-response-buffer-1("https://elpa.gnu.org/packages/" #f(compiled-function () #<bytecode -0x1c93fc9a053c2d9>) :file "dash-2.19.1.tar" :async nil :error-function #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_79> :noerror nil)
  package-install-from-archive(#s(package-desc :name dash :version (2 19 1) :summary "A modern list library for Emacs" :reqs ((emacs (24))) :kind tar :archive "gnu" :dir nil :extras ((:url . "https://github.com/magnars/dash.el") (:maintainer "Magnar Sveen" . "magnars@gmail.com") (:authors ("Magnar Sveen" . "magnars@gmail.com")) (:keywords "extensions" "lisp")) :signed nil))
  package-download-transaction((#s(package-desc :name dash :version (2 19 1) :summary "A modern list library for Emacs" :reqs ((emacs (24))) :kind tar :archive "gnu" :dir nil :extras ((:url . "https://github.com/magnars/dash.el") (:maintainer "Magnar Sveen" . "magnars@gmail.com") (:authors ("Magnar Sveen" . "magnars@gmail.com")) (:keywords "extensions" "lisp")) :signed nil) #s(package-desc :name dired-hacks-utils :version (20230512 1107) :summary "Utilities and helpers for dired-hacks collection" :reqs ((dash (2 5 0))) :kind tar :archive "melpa-devel" :dir nil :extras ((:commit . "523f51b4152a3bf4e60fe57f512732c698b5c96f") (:authors ("Matúš Goljer" . "matus.goljer@gmail.com")) (:maintainers ("Matúš Goljer" . "matus.goljer@gmail.com")) (:maintainer "Matúš Goljer" . "matus.goljer@gmail.com") (:keywords "files")) :signed nil) #s(package-desc :name dired-open :version (20230512 1107) :summary "Open files from dired using using custom actions" :reqs ((dash (2 5 0)) (dired-hacks-utils (0 0 1))) :kind tar :archive "melpa-devel" :dir nil :extras ((:commit . "523f51b4152a3bf4e60fe57f512732c698b5c96f") (:authors ("Matúš Goljer" . "matus.goljer@gmail.com")) (:maintainers ("Matúš Goljer" . "matus.goljer@gmail.com")) (:maintainer "Matúš Goljer" . "matus.goljer@gmail.com") (:keywords "files")) :signed nil)))
  package-install(dired-open)
  use-package-ensure-elpa(dired-open (t) nil)
  load-with-code-conversion("/Users/gb/.minemacs.d/config.el" "/Users/gb/.minemacs.d/config.el" nil nil)
  load("~/.minemacs.d/config.el" nil nil)
  (progn (load conf-path nil (not minemacs-verbose-p)))
  (if (file-exists-p conf-path) (progn (load conf-path nil (not minemacs-verbose-p))))
  (let ((conf-path (format "%s%s.el" minemacs-config-dir conf))) (if (file-exists-p conf-path) (progn (load conf-path nil (not minemacs-verbose-p)))))
  (if (memq conf minemacs-ignore-user-config) nil (let ((conf-path (format "%s%s.el" minemacs-config-dir conf))) (if (file-exists-p conf-path) (progn (load conf-path nil (not minemacs-verbose-p))))))
  (let ((conf (car tail))) (if (memq conf minemacs-ignore-user-config) nil (let ((conf-path (format "%s%s.el" minemacs-config-dir conf))) (if (file-exists-p conf-path) (progn (load conf-path nil (not minemacs-verbose-p)))))) (setq tail (cdr tail)))
  (while tail (let ((conf (car tail))) (if (memq conf minemacs-ignore-user-config) nil (let ((conf-path (format "%s%s.el" minemacs-config-dir conf))) (if (file-exists-p conf-path) (progn (load conf-path nil (not minemacs-verbose-p)))))) (setq tail (cdr tail))))
  (let ((tail configs)) (while tail (let ((conf (car tail))) (if (memq conf minemacs-ignore-user-config) nil (let ((conf-path (format "%s%s.el" minemacs-config-dir conf))) (if (file-exists-p conf-path) (progn (load conf-path nil ...))))) (setq tail (cdr tail)))))
  +load-user-configs(config local/config)
  load-with-code-conversion("/Users/gb/.emacs.d/init.el" "/Users/gb/.emacs.d/init.el" t t)
  load("/Users/gb/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x155cdccd2693d5>) #f(compiled-function () #<bytecode -0x1f3c61addc0d85b5>) t)
  command-line()
  normal-top-level()
```

**Screenshots**

**Additional context**
I have been using (use-package) with the :straight t option. This may be causing problem whilst I am converting my config from doom. I may simply be using (use-package) worng or something. This is also on my M1 macbook.

**Comment by abougouffa** [comment] 2023-11-22 19:04
Hello @Game-Warrior 

Yes, it is intentional, please see https://github.com/abougouffa/minemacs/issues/127#issuecomment-1809983120

Duplicate of #127

**Closed by abougouffa** 2023-11-22 19:04 UTC
